### ISSUE TITLE
OCSP stapling not properly detected

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#104]
cipherscan returns the status of ocsp stapling on a target, but this information is not returned by the api.

**Comment by 0xdiba** [comment]
It seems that the Go JSON marshaller considers boolean false values "empty" and omits them when marshalling the processed cipherscan output for archival.

Silly me had enabled 'omitempty' for all the fields in the struct.
Spent 20 minutes going mad trying to reproduce the problem against domains with ocsp_stapling enabled :no_mouth:

I'm going to change the 'omitempty's right away.
Do you want me to take some time and include the new fields I saw you have included in cipherscan output?

**Comment by jvehent** [comment]
That's odd, because the target I tested against does have ocsp stapling enabled, so the value should be true and marshalled correctly. Am I missing something?

**Comment by 0xdiba** [comment]
Send me the target and I will debug it against that then :wink: 

It is odd though because I tested it against targets like OCSP stapling enabled and I could see it
was true.

**Comment by jvehent** [comment]
Yeah, I was probably drunk when I created that issue... or maybe the ocsp response on my site was not fully loaded yet (had just done cert rotation).
In any case, this is a false positive. Sorry for the noise.

$ for i in $(seq 1 10); do tlsobs -r jve.linuxwall.info | grep OCSP; sleep 301; done
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
OCSP Stapling        true
