### ISSUE TITLE
pg NOTIFY queue is full

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#109]
This morning, the scanners are locked on this error message:
`time="2016-03-07T14:53:16+01:00" level=error msg="Could not run unacknowledged scans periodic check." error="pq: too many notifications in the NOTIFY queue" `

As far as I can tell, no processing of new scans is happening.

**Comment by 0xdiba** [comment]
It probably has something to do with the notes from [here](http://www.postgresql.org/docs/9.0/static/sql-notify.html) :

>There is a queue that holds notifications that have been sent but not yet processed by all listening sessions. If this queue becomes full, transactions calling NOTIFY will fail at commit. The queue is quite large (8GB in a standard installation) and should be sufficiently sized for almost every use case. However, no cleanup can take place if a session executes LISTEN and then enters a transaction for a very long time. Once the queue is half full you will see warnings in the log file pointing you to the session that is preventing cleanup. In this case you should make sure that this session ends its current transaction so that cleanup can proceed.

Somehow the queue got full and no cleanup could take place.
Maybe our code has a bug somewhere that prevents postgres from cleaning up the queue.
