### ISSUE TITLE
Set appropriate CORS headers on API

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#122]
Because the API doesn't currently set the proper CORS headers, I'm not able to create a WebUI in front of it.  It should set the following headers:

`Access-Control-Allow-Origin: *`  (assuming we want to let any site use the API, as CLI tools can)
`Access-Control-Allow-Methods: GET, OPTIONS, POST`  (at the very least)
`Access-Control-Max-Age: 86400`

The API also needs to respond to the OPTIONS method on all API calls with these headers, so that browsers can do a successful pre-flight CORS request.

**Comment by jvehent** [comment]
Done in https://github.com/mozilla/tls-observatory/commit/52df0591385ddb1934e8d4a04a95c9970184a09a for the scan, results and certificate endpoints.

```
$ curl -X OPTIONS -i http://localhost:8083/api/v1/scan
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, OPTIONS, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Content-Type: application/json
Date: Fri, 24 Jun 2016 10:18:35 GMT
Content-Length: 11

preflighted
```

**Comment by marumari** [comment]
Thanks for the quick turnaround on this one!  Could you let me know when it's deployed so I can start developing against it?

**Comment by marumari** [comment]
Unfortunately, the commit doesn't set the CORS headers on the GET and POST as well, so while I can submit scans, I can't see the scan_id or their results.

**Comment by 0xdiba** [comment]
You are right, the CORS headers are only set for new scans ( or rescans ) and not when cached results are returned. Also it does not handle error responses as far as I see.

**Comment by 0xdiba** [comment]
899cb90 this should do it.

**Comment by jvehent** [comment]
It was just a matter of setting the header earlier in the response code. The new code that shipped to prod now should handle that.

**Comment by marumari** [comment]
Looks great, thank you so much!
