### ISSUE TITLE
Automatically remove the https prefix in cli

### ISSUE THREAD

**Issue by centminmod** [mozilla/tls-observatory#123]
I added tlsobs to my nghttp2 docker image https://hub.docker.com/r/centminmod/docker-ubuntu-nghttp2/ but when i run it i get the following error ?

```
tlsobs -r https://twitter.com             
time="2016-06-25T14:52:49Z" level=error msg="Could not add syslog logging hook" error="Unix syslog delivery error" 
Scanning https://twitter.com (id 12117712)
Retrieving cached results from 47.503543ms ago. To run a new scan, use '-r'.

https://twitter.com does not support SSL/TLS
```

```
tlsobs -r https://centminmod.com
time="2016-06-25T14:55:46Z" level=error msg="Could not add syslog logging hook" error="Unix syslog delivery error" 
Scanning https://centminmod.com (id 12117714)
Retrieving cached results from 39.860303ms ago. To run a new scan, use '-r'.

https://centminmod.com does not support SSL/TLS
```

**Comment by jvehent** [comment]
Remove the `https://` prefix. `$ tlsobs -r twitter.com`

**Comment by centminmod** [comment]
ah ha !  thanks @jvehent

**Comment by marumari** [comment]
I had already coded this into both the CLI and web versions of the HTTP Observatory, because I kept making this same mistake myself, again and again.  :)

**Comment by bamberino** [comment]
leads this also in the message "site does not support https" on Mozilla Observatory (Beta) for https-only pages, e.g. https://mozilla.github.io/http-observatory-website/analyze.html?host=nakamastreamingcommunity.com?

**Comment by marumari** [comment]
It's very strange that this is failing:

$ tlsobs -r nakamastreamingcommunity.com
Scanning nakamastreamingcommunity.com (id 12119875)
Retrieving cached results from 1.991078429s ago. To run a new scan, use '-r'.

nakamastreamingcommunity.com does not support SSL/TLS

When it definitely does.  Perhaps some bug in the TLS Observatory?

**Comment by bamberino** [comment]
I wrote a separate issue for that so: [Issue #130 ](https://github.com/mozilla/tls-observatory/issues/130)
