### ISSUE TITLE
Use SSLLabs's client hello database to determine oldest clients

### ISSUE THREAD

**Issue by april** [mozilla/tls-observatory#129]
The mozillaEvaluationWorker is only returning level and failures; but looking at the code it seems like it should return a lot more, such as the oldest clients that are supported.

**Comment by jvehent** [comment]
The oldest clients get printed through the `AnalysisPrinter` interface, which really just maps the measured level to the Server Side TLS Guidelines. https://github.com/mozilla/tls-observatory/blob/master/worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go#L718

We could return the oldest clients in the API, or you could grab the JSON of the guidelines and do the same thing on your side. I'm open to returning it in the tlsobs api if you want, it's a simple addition.

**Comment by jvehent** [comment]
When you say `should return a lot more`, is there anything else than oldest clients you have in mind?

**Comment by marumari** [comment]
There just seem to be a lot of things in here:

https://github.com/mozilla/tls-observatory/blob/08fc009cd747be17b664955f4812990bd2058fa1/worker/mozillaEvaluationWorker/configurations.go

That don't show up through the API or anything.  The TLS thing seems like a nice list, but I end up having to loop through each cipher suite to get the list, etc.  Even just having oldest_clients would be really nice right.

Also it seems that the oldest_client output is based solely upon the various compatibility levels; there doesn't seem to be anything deeper.  I assume that's a WONTFIX, but for example something like pokeinthe.io returns nothing:

```
$ tlsobs pokeinthe.io
Scanning pokeinthe.io (id 12119744)
Retrieving cached results from 6h3m21.184641455s ago. To run a new scan, use '-r'.

--- Certificate ---
Subject  CN=pokeinthe.io
SubjectAlternativeName
- pokeinthe.io
- www.pokeinthe.io
Validity 2016-06-27T05:15:00Z to 2016-09-25T05:15:00Z
CA       false
SHA1     951D06C916A77FB0660A7C6C42804473BF2E2336
SHA256   A4EC18F605D374CBF77600F43AB573D72DDA55F7CC02F9FCBEBCFFCBC7AD23CD
SigAlg   SHA256WithRSA
Key      ECDSA 384bits P-384

--- Chain of trust ---
0:	CN=pokeinthe.io
	type: end entity
	key: ECDSA 384bits P-384
	pin-sha256: llJLhjXjqfdJrklTYSM+vWgaBa4F0PgbAMXe+VanIMc=

1:	C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
	type: intermediate CA
	key: RSA 2048bits
	pin-sha256: YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=

2:	O=Digital Signature Trust Co., CN=DST Root CA X3
	type: root CA
	key: RSA 2048bits
	pin-sha256: Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys=



--- Ciphers Evaluation ---
prio cipher                        protocols             pfs                curves
1    ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2               ECDH,P-384,384bits secp384r1
2    ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2               ECDH,P-384,384bits secp384r1
3    ECDHE-ECDSA-AES256-SHA384     TLSv1.2               ECDH,P-384,384bits secp384r1
4    ECDHE-ECDSA-AES128-SHA256     TLSv1.2               ECDH,P-384,384bits secp384r1
5    ECDHE-ECDSA-AES256-SHA        TLSv1,TLSv1.1,TLSv1.2 ECDH,P-384,384bits secp384r1
6    ECDHE-ECDSA-AES128-SHA        TLSv1,TLSv1.1,TLSv1.2 ECDH,P-384,384bits secp384r1
OCSP Stapling        true
Server Side Ordering true
Curves Fallback      false

--- Analyzers ---
* Grade: A (94/100)
* Mozilla evaluation: non compliant
  - for modern level: remove ciphersuites ECDHE-ECDSA-AES256-SHA, ECDHE-ECDSA-AES128-SHA
  - for modern level: consider adding ciphers ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-SHA384, ECDHE-RSA-AES128-SHA256
  - for modern level: remove protocols TLSv1, TLSv1.1
  - oldest clients:
```

(see the empty bottom line)

**Comment by marumari** [comment]
BTW, I am contacting SSL Labs to see if we can use this data:

https://api.ssllabs.com/api/v3/getClients

With it, we should be able to return an extremely accurate list of compatible clients, regardless of whether or not the server configuration is compliant or not.  It's the same data that SSL Labs itself uses.

**Comment by marumari** [comment]
SSL Labs has given us permission to use this data, and it's licensed under the creative commons.  Woohoo!

**Comment by jvehent** [comment]
this has been done for a while
