### ISSUE TITLE
Produce exact client support list

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#132]
Instead of just booleans, we can use SSL Lab's client data:

https://api.ssllabs.com/api/v3/getClients

To produce exact versions of what clients will be supported for any given combination of ciphers and protocols.  That way even non-compliant systems can find out their minimum client support.  They have given us permission to use this data, and it's licensed under the creative commons.

**Comment by jvehent** [comment]
Please pick one between #129 and this one, and close the other as duplicate ;)

**Comment by marumari** [comment]
I should just never use GitHub before 10am.  >_<
