### ISSUE TITLE
dv.ssl.mozqa.com hangs the TLS observatory scanner

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/tls-observatory#134]
It's been running ten minutes so far (per April) with no results yet. Works fine in browsers, assuming you have the Mozilla SHA-2 Root CA trusted.

**Comment by jvehent** [comment]
The site scans fine with cipherscan.
@0xdiba : could it be the same issue we're seeing in #130 ?

**Comment by 0xdiba** [comment]
It seems like we should update our truststores :smiling_imp: #133 
The error is `certificate signed by unknown authority` which makes sense because the Mozilla SHA-2 Root CA is not in any truststore. 
The same applies to cipherscan when used with our truststores :wink: 

Basically we have to decide if we want to add that CA.

**Comment by floatingatoll** [comment]
No worries if you don't want to trust that CA - but, er, shouldn't the scan
proceed regardless of whether it trusts the CA or not?

**Comment by floatingatoll** [comment]
Or fail. It's perfectly fine if the scan fails immediately, too. Seemingly
hanging probably is sub-optimal.

**Comment by 0xdiba** [comment]
Yes you are right, the scan is not marked as 100% completed.
I will look into that...

**Comment by jvehent** [comment]
I somehow missed that the cert is untrusted. No, we shouldn't add it to any truststore (it's an internal CA), but yes, the scan should complete anyway and return all the relevant info.

**Comment by marumari** [comment]
This is about the least trusted CA I can think of, so I agree that we should definitely not trust it.  :)

**Comment by floatingatoll** [comment]
There's a SHA-1 edition that you should trust less!

**Comment by marumari** [comment]
🍻 <-- what I need now

**Comment by 0xdiba** [comment]
@jvehent Do you think it would help if we added an error field to the scans table, so we can indicate if the target _has_tls=false_ because of an error or because of any other reason ?

**Comment by jvehent** [comment]
I think determining a failure shouldn't involve `has_tls` at all. Instead, we could use the `completion_perc` value and a new `error` column. If `completion < 100` and `error != NULL`, something went wrong.

Would that work?

**Comment by jvehent** [comment]
I found the issue by looking at the scanner logs: we hang on the chain of trust resolution.
```
time="2016-08-05T14:35:03Z" level=info msg="Received new scan" scan_id=12121956 
time="2016-08-05T14:35:04Z" level=info msg="Could not get parent" domain=dv.ssl.mozqa.com servercert=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC 
time="2016-08-05T14:35:04Z" level=info msg="Could not get parent" domain=dv.ssl.mozqa.com servercert=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC 
time="2016-08-05T14:35:04Z" level=info msg="Could not get parent" domain=dv.ssl.mozqa.com servercert=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC 
time="2016-08-05T14:35:04Z" level=info msg="Could not get parent" domain=dv.ssl.mozqa.com servercert=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC 
time="2016-08-05T14:35:04Z" level=info msg="Could not get parent" domain=dv.ssl.mozqa.com servercert=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC 
time="2016-08-05T14:35:04Z" level=warning msg="Parent not found in chain" certificate=0E25E0625BD97C91D0860B27CDB0DDE477666D45A733AADC0E5F1C7BD1F35CEC domain=dv.ssl.mozqa.com parent= 
time="2016-08-05T14:35:04Z" level=error msg="Could not get if trust is valid" cert_id=-1 error="sql: no rows in result set" scan_id=12121956 
```
