### ISSUE TITLE
add an API endpoint where an encoded certificate can be POSTed and decoded

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#141]
It would be useful to be able to POST a certificate to an endpoint and get back either the data returned by e.g. https://tls-observatory.services.mozilla.com/api/v1/certificate?id=1711994 or just an id that can then be looked up via the preexisting API.

**Comment by 0xdiba** [comment]
Implemented in 8ba16a90a8f4e3333b549e5289d0c2155b834d14
