### ISSUE TITLE
Evaluate if a certificate is technically constrained

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#143]
@mozkeeler requested we implement his contraint parsing code into the observatory. Probably the cleanest way to implement this is to write a new analysis worker specifically for this purpose, as I don't think the standard Go X509 package will support these tests, but I may be wrong.

Original code is here: https://github.com/mozkeeler/jx509/blob/master/index.js#L258

cc @jcjones and @mozmark who may have thoughts on how to best implement this in Go.

**Comment by tomato42** [comment]
I wonder if this is good direction

Problem is that Firefox and Chrome will likely start checking additional things like "is the cert signed by X CA and notBefore is earlier than <some-date>". So migrating to mozillapkix for path building and  checking may be a good idea.

**Comment by jvehent** [comment]
I don't think we can easily use mozilla::pkix with a postgres database and 4 different truststores. I generally agree that integrating with pkix would be nice to evaluate how firefox truly sees the cert, but maybe this is a different evaluation worker altogether.

The goal of this particular issue is to provide extra parsing and evaluation of their to aid with the CA program. The scope is small, so I'd prefer to implement this in isolation and not pull pkix into the mix just yet.

**Comment by jvehent** [comment]
The first part of this is easy to implement: the EKUs are already parsed by Go's x509 parser (2.5.29.37.0 is ExtKeyUsageAny and 2.16.840.1.113730.4.1 is ExtKeyUsageNetscapeServerGatedCrypto).

But we'll probably need to work with raw certificates and Go's `pkix` package to look into excluded name constraints and ip addresses in the subtrees. Those aren't parsed yet.

The best way to solve this would be to patch the standard library (anyone up for it?), but a local parser would also be acceptable.

**Comment by jcjones** [comment]
I will aim to add the name and IP constraints code to a vendorized `go` `pkix` library in the next two weeks. I'll write some things as I get started.

**Comment by jcjones** [comment]
The patch to support the IPAddress and all DNSname name constraints in crypto/x509 is here: https://github.com/jcjones/go/compare/release-branch.go1.7...jcjones:jcj-nameconstraints?expand=1

It may not be acceptable upstream, as similar patches (that do more things) [here](https://go-review.googlesource.com/#/c/21904/) and [here](https://go-review.googlesource.com/#/c/3230/) haven't landed yet.

I've an implementation of the evaluation function from above that works for a simple test certificate - it needs some more unit tests, and then I'll be ready to share it here.

**Comment by jcjones** [comment]
There is now code to perform this check in https://github.com/jcjones/gx509

When it merges into the observatory, you'll need to pull in the `vendor/` directory. How exactly you choose to track the source of that vendored package (e.g., vendoring tools) is left up to you. The simplest way is to leave the README that explains how to pull a copy.

The check is in https://github.com/jcjones/gx509/blob/master/gx509/technicalconstraints.go  - `DetermineIfTechnicallyConstrained`. There are some tests in that directory as well.

I don't plan to keep around the `gx509` repo, it's really just intended to share with you here, so please don't depend on its continued existence.

Thanks! I hope this helps.

**Comment by jvehent** [comment]
We're going to implement this in the `certificate` package directly and apply the evaluation logic to every certificate parsed. The results will be stored as columns of the `certificate` table in 4 new columns:
* `is_contrained` will be a boolean
* `permitted_names` and `excluded_names` will be `[]string`
* `permitted_ips` and `excluded_ips` will be `[]net.IPNet`

We will also repopulate historical data in DB using a fork of https://github.com/mozilla/tls-observatory/blob/master/tools/fixExtensions.go

**Comment by jvehent** [comment]
This has now been merged with #183 and certificates in database are being updated.
