### ISSUE TITLE
add a field to aid in identifying CAs by name/spki

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#144]
Sometimes CAs have multiple different certificates that nonetheless represent the same logical CA. It would be nice to have a field like 'certID' that is something like SHA-256(der of name + der of spki).

**Comment by jvehent** [comment]
We have a field with the public key hash. Would that fulfill your use case?

**Comment by mozkeeler** [comment]
Well, we could probably implement it in terms of that, but I think the idea is that it would be a single identifier that would make these two CAs identical:

{ issuer: "Foocorp Root CA", subject: "Foocorp Root CA", spki: [some key], ...}
{ issuer: "Cross-sign CA", subject: "Foocorp Root CA", spki: [same key], ...}

but these would be distinct:

{ issuer: "Foocorp Root CA", subject: "Foocorp Root CA", spki: [some key], ...}
{ issuer: "Foocorp Root CA", subject: "Foocorp Root CA-Bv3 Final Final", spki: [same key], ...}

(since for a certificate to be issued by another one, the issuer/subject have to match)

**Comment by jvehent** [comment]
That seems reasonable. Could you share some pseudo code (or, even better, a patch) ?
That would most likely go in the cert parsing code here: https://github.com/mozilla/tls-observatory/blob/master/certificate/certificate.go#L406-L471

**Comment by sleevi** [comment]
@jvehent 

```go
func CertIDHash(cert* x509.Certificate) string {
  h := sha256.New();
  h.Write(cert.RawSubject);
  h.Write(cert.RawSubjectPublicKeyInfo);
  return base64.StdEncoding.EncodeToString(h.Sum(nil));
```

**Comment by jvehent** [comment]
This is live:
```bash
$ curl -s https://tls-observatory.services.mozilla.com/api/v1/certificate?id=42 | jq -r '.hashes.sha256_subject_spki'
065D43F4C81B18BE6989435AEA98144938DB896DC9EB6573BF219CDEC2AF6D80
```
The backfill of the certificates table will take a couple days, as the script needs to update the sha256_subject_spki field in all 2M certs in the DB.
