### ISSUE TITLE
include serial number in decoded certificate json

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#152]
As far as I can tell, the json generated from decoding a certificate doesn't include the serial number, which would be fairly useful (e.g. often certificates are identified as just (issuer, serial number) pairs).

**Comment by jvehent** [comment]
We have a field for it in the database, but it doesn't get parsed when inserted at the moment. I will write a patch for it.

Which format should we use? In Go, it's a bigint and openssl represents it as hexadecimal. Should the API return the serial in hex or some other format?

**Comment by jvehent** [comment]
for my own notes
```go
package main

import (
	"encoding/hex"
	"fmt"
	"math/big"
)

func main() {
	bigint := new(big.Int)
	bigint.SetString("5498732196879865438973138794318978963189", 10)
	fmt.Println(hex.EncodeToString(bigint.Bytes()))
}
```
outputs `1028c94ca6608eaa765b3a27af556956f5`

**Comment by mozkeeler** [comment]
I think hex is good (like you have in that example)

**Comment by jvehent** [comment]
Patch deployed to prod, database update in progress.
