### ISSUE TITLE
certificate json including spurious crlDistributionPoint extension?

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#155]
The json returned from https://tls-observatory.services.mozilla.com/api/v1/certificate?id=11 lists crlDistributionPoint among the x509v3Extensions, but if you examine the certificate, that extension isn't present.

**Comment by floatingatoll** [comment]
To clarify, it lists:

"crlDistributionPoint": null

**Comment by jvehent** [comment]
Fix deployed to prod.
