### ISSUE TITLE
All scans need 2 attempts

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#162]
I think we may have a concurrency bug in the way notifications are routed to scanners. Looking through the DB for the last 60 days of scans, I can't find a single one that ran correctly at the first attempt.

``` sql
observatory=> select attempts, count(*) from scans where timestamp > NOW() - INTERVAL ' 60 days' group by attempts;
 attempts |  count  
----------+---------
        2 | 1180930
        3 |   24144
        4 |       3
(3 rows)
```

The fact that we always succeed at the second attempt, and that there isn't ever a delay (normal requeueing takes 10 minutes), indicates both scanners pick up the scan and increase the attempt count simultaneously.

I read through the code for a long time but can't spot a bug in the logic. The most likely cause for this problem is `SELECT...FOR UPDATE` not behaving correctly, but that seems unlikely.

**Comment by jvehent** [comment]
I think this bug may have caused multiple certificates with the same sha256 fingerprint to be inserted in database, probably due to a race condition between the insert and the update of the sha256 index. I added a uniqueness constraint to prevent this from happening.

```sql
ALTER TABLE certificates ADD CONSTRAINT certificates_unique_sha256_fingerprint UNIQUE (sha256_fingerprint);
```

**Comment by 0xdiba** [comment]
This happens only in the last months?
It would be really weird if this has been going on for the whole year the service is running.

**Comment by jvehent** [comment]
I think this has been going on for a while, I just limited my query to the last 2 months so it wouldn't take forever and was guaranteed to involve the latest code.

**Comment by autrilla** [comment]
This actually has a pretty simple explanation: `db.NewScan` creates the scan with `attempts` set to 1: https://github.com/mozilla/tls-observatory/blob/master/database/database.go#L79-L83
