### ISSUE TITLE
Integrate ev-checker as an analysis worker in the scanner

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#163]
[ev-checker](https://github.com/mozkeeler/ev-checker/) is a tool that verifies a chain matches specific criteria needed to be treated as Extended Validation in NSS. The seceng team uses ev-checker as part of verifying a CA is properly setup for EV.

ev-checker is a c++ app and rewriting it in Go would be impractical. I propose we call it as an external program from an analysis worker that will act as a wrapper. The worker would run with other analysis workers in the scanner.

The trick is passing some parameters to the ev-checker worker. We currently don't pass parameters that far down the scanning chain. I think to achieve this we'll need the following:
* access analysis parameters in the `POST /api/v1/scan` endpoint
* store analysis parameters as a new `jsonb` column of the `scan` table
* retrieve those parameters in the scanner and only call the `ev-checker` worker if the needed params are set

cc @mozkeeler and @jcjones for info

**Comment by autrilla** [comment]
I'd like to work on this

**Comment by jvehent** [comment]
This is now live at https://tls-observatory.services.mozilla.com/static/ev-checker.html
