### ISSUE TITLE
API endpoints to dump the content of a truststore

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#164]
We should have an API endpoint that dumps the content of a truststore in various format:
* as an array of certificates in json format
* as text file containing a list of PEM encoded certs

**Comment by autrilla** [comment]
@jvehent when you said `as an array of certificates in json format`, should each entry in the JSON array be ascii-armored, or do you want some other encoding?

**Comment by jvehent** [comment]
The json output should just dump an `[]certificate`, so an array of these: https://tls-observatory.services.mozilla.com/api/v1/certificate?id=42

The text output should just dump a text file with each armored certificate after the other, like https://github.com/mozilla/tls-observatory/blob/master/conf/truststores/CA_mozilla_nss.crt
