### ISSUE TITLE
TLS Observatory is currently down

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#168]
I get 500/400 errors, respectively, for creating new scans or calling the API.

**Comment by 0xdiba** [comment]
Are you still seeing this?

Seems to work ok for me.

**Comment by autrilla** [comment]
I think this was fixed by https://github.com/mozilla/tls-observatory/pull/169

**Comment by 0xdiba** [comment]
You're right. I didn't make the connection.
Closing this one.
