### ISSUE TITLE
negative serial numbers not indicated

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#184]
This certificate has a serial number that is negative, but https://tls-observatory.services.mozilla.com/api/v1/certificate?id=1821301 isn't indicating that this is the case:

    -----BEGIN CERTIFICATE-----
    MIICNjCCAeCgAwIBAgIQgHCUCGAAkJMR0ub/9x4viDANBgkqhkiG9w0BAQQFADB9
    MQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZp
    ZXcxJTAjBgNVBAoTHE5ldHNjYXBlIENvbW11bmljYXRpb25zIENvcnAxDTALBgNV
    BAsTBEFQTUMxEzARBgNVBAMTClJ1c2xhbkF1dGgwHhcNOTkwMzMxMDAzMzA3WhcN
    MDQwMzMxMDAzMzA3WjB9MQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNV
    BAcTDU1vdW50YWluIFZpZXcxJTAjBgNVBAoTHE5ldHNjYXBlIENvbW11bmljYXRp
    b25zIENvcnAxDTALBgNVBAsTBEFQTUMxEzARBgNVBAMTClJ1c2xhbkF1dGgwXDAN
    BgkqhkiG9w0BAQEFAANLADBIAkEAxu9LmRU3GHSS9q/TQbF4iNZhbNETm0Jg+NzA
    /5QSY59YYAfitOEyc9gkrtQ3ZUJWhiZeLR+4/75YVQaY1/wRAwIDAQABozwwOjAL
    BgNVHQ8EBAMCAcQwDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQURK5ym9yBRRjrO1yX
    /dPjZc2Vyu0wDQYJKoZIhvcNAQEEBQADQQCsaps5vJ3eRQPx1gGaah6yCOfviIj0
    wSo4P9N2TvXyAnxV7GZGc+9kqGejHVTdFcG9K1Ygjz/azvd3Jpsee0dc
    -----END CERTIFICATE-----

**Comment by jvehent** [comment]
There is a bug in the certificate parser. We use
```go
stored.Serial = strings.ToUpper(hex.EncodeToString(cert.SerialNumber.Bytes()))
```
where `cert.SerialNumbercert.SerialNumber` is a `bigint` and the `Bytes()` method "returns the absolute value of x as a big-endian byte slice."

Using `fmt.Sprintf()` is [much simpler](https://play.golang.org/p/G3Op7t9KzS), I'll push a patch.

**Comment by jvehent** [comment]
This is now live. 
```
$ curl -s -X POST -F certificate=@/tmp/negcert.pem https://tls-observatory.services.mozilla.com/api/v1/certificate | jq '.serialNumber'
"-7F8F6BF79FFF6F6CEE2D190008E1D078"
```
