### ISSUE TITLE
add an API to validate signatures?

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/tls-observatory#189]
Apparently some entries in the CCADB were added with invalid signatures, suggesting it might be useful to have an API to validate signatures. (ccing @WilsonKathleen for more details)

**Comment by jvehent** [comment]
Do you mean intermediate certs that should be validated against their
issuers?
That's probably something we should add to the post certificate endpoint.

**Comment by floatingatoll** [comment]
This thread seems on point:

https://groups.google.com/forum/m/#!topic/mozilla.dev.security.policy/ABcyJ0XwV2Q

**Comment by floatingatoll** [comment]
Also https://groups.google.com/forum/m/#!topic/mozilla.dev.security.policy/rnXbWfUztM8

**Comment by jvehent** [comment]
The `POST /api/v1/certificate` endpoint already validates signatures and returns the ID of the issuer in the JSON of the posted certificate.
```bash
$ curl -s -X POST -F certificate=@webextensions.settings.services.mozilla.com-20180102.crt https://tls-observatory.services.mozilla.com/api/v1/certificate | jq '.issuer.id'
466

$ curl -s https://tls-observatory.services.mozilla.com/api/v1/certificate?id=466 | jq '.subject.cn'
"DigiCert SHA2 Secure Server CA"
```

The `GET /api/v1/paths` endpoint also returns the full certificate paths to known roots, regardless of truststore.

Both of these methods verify signatures using this code: https://github.com/mozilla/tls-observatory/blob/master/database/certificate.go#L589-L592

To make use of them, you simply need to post an intermediate to the observatory and verify the issuer matches the expected root, either by using the JSON response from the call to `POST /api/v1/certificate`, or by walking through the paths from `GET /api/v1/paths`.

Does this solve your needs? If so, we can close this issue, or implement something else.

**Comment by mozkeeler** [comment]
I think so - the code that creates the CCADB entries should be able to use what we already have to double-check that the issuer is the expected certificate.
