### ISSUE TITLE
paths building fails for some cert

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#190]
Here is an example of one that always times out:

https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=2103

I've heard that Comodo/Cloudflare certs tend to have this issue.

**Comment by jvehent** [comment]
The issue most likely is in the `/api/v1/paths` endpoint.

**Comment by marumari** [comment]
"paths building fails for some cert", huh.  Better make sure to double-check those Enigma slides.  ;)

**Comment by jvehent** [comment]
This was fixed a while back, it was an issue with infinite loops in paths. (webpki ftw!)
![screenshot_2017-03-12_10-56-59](https://cloud.githubusercontent.com/assets/415617/23832787/ab702fb2-0712-11e7-8956-e5d0c4028a8f.png)
