### ISSUE TITLE
any way to use a own copy of server-side-tls-conf.json?

### ISSUE THREAD

**Issue by rzmf** [mozilla/tls-observatory#193]
In https://github.com/mozilla/tls-observatory/pull/102#issuecomment-184386474 this was mentioned but never coded, or did i missed this?

**Comment by 0xdiba** [comment]
For the [hosted service](http://tls-observatory.services.mozilla.com/) No, you cannot change it.

If you are compiling on your own you can change https://github.com/mozilla/tls-observatory/blob/master/worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go#L31 to point to your own hosted file. 
You can even set the URL to something that fails ( probably any other valid or invalid URL 😃  ) and the system will automatically fall back to [this file](https://github.com/mozilla/tls-observatory/blob/master/worker/mozillaEvaluationWorker/configurations.go) which you can change at will.

**Comment by rzmf** [comment]
I run my own copy of scanner/api/"cli" as docker images.

Which part of the three actually does the download?

**Comment by 0xdiba** [comment]
The download is performed by the scanner.

**Comment by rzmf** [comment]
ok, thanks for info.
A new option in scanner.cfg and commandline would be nice

**Comment by rzmf** [comment]
You are sure about the download by the scanner?

# docker run -ti --rm mozilla/tls-observatory
root@f56cf65011bd:/go# tlsobs
time="2017-01-19T11:53:07Z" level=error msg="Get https://statics.tls.security.mozilla.org/server-side-tls-conf.json: dial tcp 54.240.162.44:443: i/o timeout"
time="2017-01-19T11:53:07Z" level=error msg="Could not get tls confs from url - fallback to locally saved configurations"

note that no observatory  (as in reachable api) was given and that tlsobs does not reach public internet

**Comment by jvehent** [comment]
We should fix that, the tlsobs client doesn't use the JSON file. The reason it downloads it is because the tlsobs client imports the mozillaEvaluationWorker to print the analysis results, and the worker downloads the JSON file in its init function. That's only used when the worker runs as part of the scanner, but because init() is always executed when a program start, the tlsobs client ends up downloading it as well.

**Comment by 0xdiba** [comment]
Oh. I didn't think of that.
We should probably move any setup code to either the first time `worker.Run` is executed or to a new function of the worker interface ( e.g. `setup` ) that gets called by the scanner for all registered workers.

**Comment by rzmf** [comment]
it does work, but it slows down the start of the request of the scan from the api. If api&scanner also try to download the file.....

**Comment by jvehent** [comment]
How about using `sync.Once` ? https://golang.org/pkg/sync/#Once

**Comment by rzmf** [comment]
#195 solved the mandatory download for the server-side-tls-conf.json.

Could you additionally add a config option for the URL where this file gets  fetched?
