### ISSUE TITLE
Use CA CRLs to check revocation status

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#212]
Loads of certificates are revoked before the end of their validity period. We should check for revocation status using the CRLs provided by CAs, and maybe even run OCSP queries.

The CRLs should be reloaded regularly. We can either keep them in memory or load them in a new table.

Probably the best way to implement this is in a separate worker that modifies the certificate and trust tables.

**Comment by 0xdiba** [comment]
Fixed with 8791a200eb40f8625a152bfb8336171305f5f35c
