### ISSUE TITLE
Not recognising ciphers

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#225]
Hi,

I have setup my nginx config to match the modern config using the "Mozilla SSL Configuration Generator".

My ciphers in nginx look like so:

`ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';`

But when I run TLS Observatory against this server (using the latest docker image), the output is:

> --- Ciphers Evaluation ---
prio cipher                      protocols pfs                curves
1    ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2   ECDH,P-384,384bits secp384r1
2    ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2   ECDH,P-384,384bits secp384r1
3    ECDHE-RSA-AES256-SHA384     TLSv1.2   ECDH,P-384,384bits secp384r1
4    ECDHE-RSA-AES128-SHA256     TLSv1.2   ECDH,P-384,384bits secp384r1
OCSP Stapling        false
Server Side Ordering true
Curves Fallback      false
>
>--- Analyzers ---
>* Mozilla evaluation: intermediate
>- for modern level: consider adding ciphers ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES256-SHA384, ECDHE-ECDSA-AES128-SHA256`

However, all of those ciphers are listed in the nginx config but it looks like TLS observatory isn't picking them up. Is there any troubleshooting I can do? 

Server is Ubuntu 16.04 with OpenSSH version:

OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g 1 Mar 2016

Thanks for the help!

**Comment by tomato42** [comment]
OpenSSL 1.0.2 does not support Chacha20 ciphers.
ECDHE-ECDSA ciphers require a secondary ECDSA certificate (see [here](https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/))

Looks like it works exactly as expected.
