### ISSUE TITLE
Investigate quotes removal bug in cert subject/issuer

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#247]
[This intermediate from Thawte](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=779) has the subject `Subject: C = US, O = "Thawte, Inc.", CN = Thawte SSL CA` when parsed by `openssl x509`. However, TLS Observatory stores it without the double quotes and returns the string `/C=US/O=Thawte, Inc./CN=Thawte SSL CA`. The double quotes are part of the cert and should not be removed, so this is a bug either in TLS Observatory, or in Go's x509.

**Comment by adamdecaf** [comment]
The docker image `OpenSSL 1.1.0f  25 May 2017` prints this with quotes. 

This actually looks like a fairly recent change in openssl. 

```
$ /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2n  7 Dec 2017
$ /usr/local/opt/openssl/bin/openssl x509 -in thawte.pem -noout -text | grep -E 'Issuer:|Subject:' 
        Issuer: C=US, O=thawte, Inc., OU=Certification Services Division, OU=(c) 2006 thawte, Inc. - For authorized use only, CN=thawte Primary Root CA
        Subject: C=US, O=Thawte, Inc., CN=Thawte SSL CA


$ openssl version
LibreSSL 2.6.4
$ openssl x509 -in thawte.pem -noout -text | grep -E 'Issuer:|Subject:' 
        Issuer: C=US, O=thawte, Inc., OU=Certification Services Division, OU=(c) 2006 thawte, Inc. - For authorized use only, CN=thawte Primary Root CA
        Subject: C=US, O=Thawte, Inc., CN=Thawte SSL CA
```

**Comment by adamdecaf** [comment]
Just to double check - Does tls-observatory do any special handing/printing of asn1 values? I haven't see any in the code so far.

**Comment by tomato42** [comment]
Should it really have " in name? I don't see it here 
https://crt.sh/?q=73E42686657AECE354FBF685712361658F2F4357

I think it's just openssl adding them so that you can actually parse the DN (and not interpret the comma in the name as DN object separator but rather as part of the organizationName)

**Comment by adamdecaf** [comment]
It looks like a formatting change in 1.1.0.

https://mta.openssl.org/pipermail/openssl-users/2018-March/007674.html

**Comment by jvehent** [comment]
I'm ok with following what crt.sh does, and not include the quotes.
