### ISSUE TITLE
Docker tlsobs-api

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#249]
When starting the tlsobs-api using the latest docker image, I get a permission denied error:

> app@c9d4c73259b2:/etc/tls-observatory$ tlsobs-api
>{"Timestamp":1503310130393846821,"Time":"2017-08-21T10:08:50Z","Type":"app.log","Logger":"tlsobs-api","Hostname":"c9d4c73259b2","EnvVersion":"2.0","Pid":62,"Fields":{"msg":"Listening on"}}
{"Timestamp":1503310130396088241,"Time":"2017-08-21T10:08:50Z","Type":"app.log","Logger":"tlsobs-api","Hostname":"c9d4c73259b2","EnvVersion":"2.0","Pid":62,"Fields":{"msg":"listen tcp :80: bind: permission denied"}}`

However, in order to debug this issue I can't find where this app.log is? 

I don't have sudo installed in the docker image either if that helps.

Thank you!

**Comment by autrilla** [comment]
I can't reproduce this. I run

```
❯ docker run --name tlsobs-postgres -e POSTGRES_PASSWORD=mysecretpassphrase -e POSTGRES_USER=tlsobsapi -e POSTGRES_DB=observatory -p 5432:5432 -d postgres

❯ docker run -p 8083:8083 --name tlsobs-api --link tlsobs-postgres:tlsobs-postgres -ti mozilla/tls-observatory /bin/bash
app@adb626dd3f60:~$ export TLSOBS_POSTGRES="tlsobs-postgres:5432"
app@adb626dd3f60:~$ /app/tlsobs-api
{"Timestamp":1503333180186665496,"Time":"2017-08-21T16:33:00Z","Type":"app.log","Logger":"tlsobs-api","Hostname":"adb626dd3f60","EnvVersion":"2.0","Pid":10,"Fields":{"msg":"Listening on :8083"}}
{"Timestamp":1503333180863511413,"Time":"2017-08-21T16:33:00Z","Type":"app.log","Logger":"tlsobs-api","Hostname":"adb626dd3f60","EnvVersion":"2.0","Pid":10,"Fields":{"msg":"x-forwarded-for=[] GET HTTP/1.1 /__heartbeat__ user-agent=curl/7.54.0 req-id=HMX2DJJR"}}
^C
```

And it works fine. It looks like your API is listening on the empty string, so that's not right. Make sure your configuration file has APIListenAddr configured right, like in the example https://github.com/mozilla/tls-observatory/blob/master/conf/api.cfg#L28, or alternatively override that with an environment variable by running `export TLSOBS_APILISTENADDR=":8083"`.

**Comment by jammasterj89** [comment]
Thank you. My api.cfg file did not contain the last line "APIListenAddr   = ":8083". I've added it in and it runs fine now.

This was my fault due to having a my own script to start the api automatically which was using an old local version of cipherscan.

Sorry about that!
