### ISSUE TITLE
Update TLS Observatory Parser Linting: Cert Lint into TLS Observatory

### ISSUE THREAD

**Issue by jcjones** [mozilla/tls-observatory#257]
Similar but different to #187, this is to integrate the [AWS Labs Cert Lint tool](https://github.com/awslabs/certlint)'s output into the certificate parser's output.

The integration is expected to be via a shell execution of the other utility. If we need to do something more exotic (RPC to a Docker instance, for example), that should be a follow-up. For now, this issue should assume we can call out to the executable and read the results from `stdout`.

**Comment by adamdecaf** [comment]
I'd be open to trying this. Would `tls-observatory` need to worry about cloning and installing `certlint`? 

Would this be in a new worker? (Either one worker per cert lint tool or all tools under one worker.)

**Comment by jvehent** [comment]
I think this would be a new worker, probably similar to `evChecker` that also executes a separate binary. The docker image will need to retrieve and build `certlint` as part of the travisci run.
