### ISSUE TITLE
Add suppport for DNS CAA records

### ISSUE THREAD

**Issue by vin01** [mozilla/tls-observatory#259]
https://www.digicert.com/blog/new-caa-requirement-2/

> Effective September 2017, all CAs will be required to check and abide by CAA records.

I believe it will be a good plus to the observatory.

An existing go project for the same I could find - https://github.com/weppos/dnscaa.

**Comment by jvehent** [comment]
So, here's the plan for implementing this feature:

1. Create a new "caa" worker that:
  a. retrieve the CAA record of a target, or its parent domain until one is found or the root is reached
  b. parse all the records (CAA values) into a struct
  c. find the record that applies to the current target
  d. verify the end-entity certificate is issued by the CA identified by the record that applies to the target

2. Implement an `Assertor` to allow the runner to verify CAA status on a target

**Comment by floatingatoll** [comment]
Do we use that same "test all parent domains recursively until exhausted"
logic elsewhere in the Observatory? I ask only because one of our other
community projects here maintains a list of "top level domains" to ease
this task, in case it's of any value to you.

**Comment by 0xdiba** [comment]
@jvehent I can work on this this week if you haven't already started working on it.

**Comment by jvehent** [comment]
>  one of our other community projects here maintains a list of "top level domains" to ease this task

I'm not sure how that would help. All we really need to do is take www.foo.bar.baz and check CAA on
- www.foo.bar.baz
- foo.bar.baz
- bar.baz
_(- baz ? that sounds nuts we'd have a CAA on a TLD, but I don't know if the RFC forbids it)_
which is pretty straighforward to implement.

> @jvehent I can work on this this week if you haven't already started working on it.

I started poking at it, but just enough to understand what need to be implemented. Feel free to pick it up.
I would use `github.com/miekg/dns` and steal some of the code from https://github.com/weppos/dnscaa/blob/master/dnscaa.go, though I find their lookup function overly complicated.

**Comment by jvehent** [comment]
Well,  what do you know, looks like a TLD can have a CAA, so our recursive checks needs to go that far. https://twitter.com/jvehent/status/907591714927517696

**Comment by 0xdiba** [comment]
Nice catch! 

> I would use github.com/miekg/dns and steal some of the code from https://github.com/weppos/dnscaa/blob/master/dnscaa.go, though I find their lookup function overly complicated.

I too don't think its worth it adding a dependency just for that.

I will prepare a PR and see how it works out!

**Comment by 0xdiba** [comment]
I think we need a way to match issuer domains found in CAA records, with actual CA CNs and/or OUs.

At first I tried fuzzy matching the string found in CAA records with the CA OU but that doesn't seem to do the trick.

@jvehent Are you aware of any list of that kind?
