### ISSUE TITLE
Some certificates return a serial number with missing leading zeroes

### ISSUE THREAD

**Issue by christopher-henderson** [mozilla/tls-observatory#291]
The CCADB has these with leading zeroes. The encoding/asn1 package is also return leading zeroes on these certificates.

D86A18B5F76952B736E89A2DB3F0FDF9070711460114B6A08D649CA627935C96
&nbsp;&nbsp;&nbsp;&nbsp;[crt.sh](https://crt.sh?q=D86A18B5F76952B736E89A2DB3F0FDF9070711460114B6A08D649CA627935C96)
&nbsp;&nbsp;&nbsp;&nbsp;[certsplainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?sha256=D86A18B5F76952B736E89A2DB3F0FDF9070711460114B6A08D649CA627935C96)
1C551005D7A178DB89AD5AA145742FF4EB37F88A8E77F3AD4C8347A5EED4DBF4
&nbsp;&nbsp;&nbsp;&nbsp;[crt.sh](https://crt.sh?q=1C551005D7A178DB89AD5AA145742FF4EB37F88A8E77F3AD4C8347A5EED4DBF4)
&nbsp;&nbsp;&nbsp;&nbsp;[certsplainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?sha256=1C551005D7A178DB89AD5AA145742FF4EB37F88A8E77F3AD4C8347A5EED4DBF4)
5AE464BD2F83901FC33EF2B50CD880F5118C8DBEB1EB4A4E94B2FB05128805C2
&nbsp;&nbsp;&nbsp;&nbsp;[crt.sh](https://crt.sh?q=5AE464BD2F83901FC33EF2B50CD880F5118C8DBEB1EB4A4E94B2FB05128805C2)
&nbsp;&nbsp;&nbsp;&nbsp;[certsplainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?sha256=5AE464BD2F83901FC33EF2B50CD880F5118C8DBEB1EB4A4E94B2FB05128805C2)
FB1147E7AB97A29BB9C1140ABF3DE831F4C5F60D11B90FEC999A0816375D8457
&nbsp;&nbsp;&nbsp;&nbsp;[crt.sh](https://crt.sh?q=FB1147E7AB97A29BB9C1140ABF3DE831F4C5F60D11B90FEC999A0816375D8457)
&nbsp;&nbsp;&nbsp;&nbsp;[certsplainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?sha256=FB1147E7AB97A29BB9C1140ABF3DE831F4C5F60D11B90FEC999A0816375D8457)
A9B5698C5263BEFF3D60720DC1844CB95D16F06E04268BCE3BE4D60282B01EF9
&nbsp;&nbsp;&nbsp;&nbsp;[crt.sh](https://crt.sh?q=A9B5698C5263BEFF3D60720DC1844CB95D16F06E04268BCE3BE4D60282B01EF9)
&nbsp;&nbsp;&nbsp;&nbsp;[certsplainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?sha256=A9B5698C5263BEFF3D60720DC1844CB95D16F06E04268BCE3BE4D60282B01EF9)

I believe this to be another caching issue, similar to the EKUs at issue #289 .

I made [this certificate](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=186622767) with the exact same serial number as [this fella](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=109984338) and got the leading zeroes back just fine. As such, I reckon these certs are a stale cache from the time before [this change](https://github.com/mozilla/tls-observatory/commit/391e8bb2417f84f49c3a06bf8dddd90ad4089ec5).

**Comment by WilsonKathleen** [comment]
I believe that this issue has been resolved, so can be closed. Thanks!
