### ISSUE TITLE
Build error on Go 1.10 caused by go vet

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#300]
I run the Docker version of tls-obs daily using the latest tag, and as of yesterday I am getting an error when running "make".

I raised an [issue](https://github.com/mozilla/tls-observatory/issues/248) last year around the "tlsobs" binary being missing. Since then I have been running "make" within  "/go/src/github.com/mozilla/tls-observatory" in the container to produce the tlsobs binary within "/go/bin". Unfortunately I am now seeing the following error?

> GOOS=linux GOARCH=amd64 go test github.com/mozilla/tls-observatory/worker/mozillaEvaluationWorker/
FAIL	github.com/mozilla/tls-observatory/worker/mozillaEvaluationWorker [build failed]
github.com/mozilla/tls-observatory/worker/mozillaEvaluationWorker
worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go:235: Sprintf call has arguments but no formatting directives
Makefile:46: recipe for target 'test' failed
make: *** [test] Error 2

Thanks for the help!

**Comment by jvehent** [comment]
I'll have a fix for it shortly

**Comment by jvehent** [comment]
this was fixed in 1.2.36. `docker pull` will give you an image that has the go vet issues fixed, and the tlsobs binary included under /go/bin and /app

**Comment by jammasterj89** [comment]
@jvehent @autrilla Thank you for the quick fix, working as expected now :)
