### ISSUE TITLE
Chacha20 is not detected

### ISSUE THREAD

**Issue by Darkspirit** [mozilla/tls-observatory#301]
https://observatory.mozilla.org/analyze.html?host=perfektesgewicht.de#tls
vs. https://www.ssllabs.com/ssltest/analyze.html?d=perfektesgewicht.de&hideResults=on

**Comment by jvehent** [comment]
The issue lies in cipherscan which needs a better version of openssl (while still supporting old ciphers).
https://github.com/mozilla/cipherscan/issues/118
