### ISSUE TITLE
a certificate mismatch is not red

### ISSUE THREAD

**Issue by Darkspirit** [mozilla/tls-observatory#310]
https://observatory.mozilla.org/analyze/webassembly.org#tls
https://www.hardenize.com/report/webassembly.org/1521224132#www_certs

**Comment by jvehent** [comment]
tlsobs returns `is_valid: false` on cert mismatch, you can see that in the `tlsobs` command line. The issue is the frontend doesn't check `is_valid`. cc @april and I'll create an issue in the observatory frontend.
