### ISSUE TITLE
Could not create new scan

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/tls-observatory#317]
I have TLS and HTTP obs running locally, and as of Mar 24, 2018 I have just started seeing this error (no changes were made when running _docker pull mozilla/tls-observatory_ beforehand):

    app@37366f0494d5:~$` tlsobs -observatory http://10.220.109.121:8083 -r google.co.uk
    2018/03/26 09:48:22 Scan failed. HTTP 500: Could not create new scan: pq: column "scan_error" of relation "scans" does not exist
    pq: column "scan_error" of relation "scans" does not exist

Now looking at my psql db it looks to be true, I can't see a scan_error column anywhere:

    observatory=# \d scans
                                            Table "public.scans"
          Column      |            Type             |                     Modifiers
    ------------------+-----------------------------+----------------------------------------------------
     id               | integer                     | not null default nextval('scans_id_seq'::regclass)
     timestamp        | timestamp without time zone | not null
     target           | character varying           | not null
     replay           | integer                     |
     has_tls          | boolean                     | not null
     cert_id          | integer                     |
     trust_id         | integer                     |
     is_valid         | boolean                     | not null
     completion_perc  | integer                     | not null
     validation_error | character varying           | not null
     conn_info        | jsonb                       | not null
     ack              | boolean                     | not null
     attempts         | integer                     |
     analysis_params  | jsonb                       | not null

I am a bit confused as nothing has changed as far as I can tell, is there any troubleshooting I can do anyone knows of please? 

Apologies for raising this issue as I am running everything locally on the same server: postgres db, observatory and docker containers for tls observatory.

**Comment by adamdecaf** [comment]
I think you'll have to create that column manually. It was added in https://github.com/mozilla/tls-observatory/commit/dae116330ec186d8f744d9357f3b74e789f52b69#diff-88655de7e12d7fa28ebbde6309bc75c2L80 Something like the following would probably work: 

```
alter table scans add column scan_error       varchar NOT NULL; 
```

I asked about this over in https://github.com/mozilla/tls-observatory/pull/309#issuecomment-373845045. We should probably add a migration tool.

**Comment by jvehent** [comment]
This is correct. And I'm +1 on the migration tool, but not decided on which approach to take. Maybe a schema_version column in a version table, with a panic at startup, would be enough?

**Comment by jammasterj89** [comment]
@adamdecaf @jvehent thank you for the help, I ran the alter table but saw this error:

    ERROR:  column "scan_error" contains null values

So I had to set a default value like so:

    alter table scans add column scan_error       varchar NOT NULL default 'defaulterror';

However, now when I run a scan it just hangs on 

     "Scanning google.co.uk (id 672)"

When I look in the db the data inserted looks like so:

     id  |         timestamp          |    target    | replay | has_tls | cert_id | trust_id | is_valid | completion_perc | validation_error | conn_info | ack | attempts | analysis_params | scan_error
    -----+----------------------------+--------------+--------+---------+---------+----------+----------+-----------------+------------------+-----------+-----+----------+-----------------+------------
     672 | 2018-03-27 09:56:34.082669 | google.co.uk |     -1 | f       |         |          | f        |               0 |                  | null      | f   |        0 | {}              |
    (1 row)

**Comment by jvehent** [comment]
This is odd... I can't reproduce it on my local dev. I dropped and re-added the table, and a scan succeeded without issue:

```sql
observatory=# alter table scans drop column scan_error ;
ALTER TABLE
observatory=# alter table scans add column scan_error varchar;
ALTER TABLE
```
```
$ tlsobs -observatory http://localhost:8083 tls-observatory.services.mozilla.com
Scanning tls-observatory.services.mozilla.com (id 44)
... all results show up after a minute```

**Comment by jammasterj89** [comment]
@jvehent Thank you, I've stopped and restarted the tlsobs API container, dropped the column and added it as per your comment, and now it is able to scan. Not sure if it was my "default" command or the fact that the API container needed restarting, but either way it is working. Thanks for the help :)
