### ISSUE TITLE
permalinks in Certificate Explainer

### ISSUE THREAD

**Issue by hihellobolke** [mozilla/tls-observatory#320]
Certificate Explainer generates permalinks, add option to disable permalink generation. 

It's possible to enumerate these certs and so it may expose dns/san information for certs inadvertently.

Example: https://tlsobservatory.services.mozilla.com/static/certsplainer.html?id=1

**Comment by adamdecaf** [comment]
I think you mean https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=1

> It's possible to enumerate these certs and so it may expose dns/san information for certs inadvertently.

Certificate Transparency logs have the same information and are required by chrome. I don't see this as an issue specific to tls-observatory.

**Comment by hihellobolke** [comment]
Thanks, I guess I will close this one 👍
