### ISSUE TITLE
Docker Compose file doesn't work because dockerfiles were removed from tools

### ISSUE THREAD

**Issue by wraithfive** [mozilla/tls-observatory#349]
Trying to spin up local version using the docker-compose file in the project but it depends on docker files that were removed in PR #332 

`ALMPC02TL255GTF1:tls-observatory$ docker-compose up
Building postgres
ERROR: Cannot locate specified Dockerfile: tools/Dockerfile-postgres
`

**Comment by jvehent** [comment]
We don't really support docker compose right now. I'd recommend following the development docs instead: https://github.com/mozilla/tls-observatory#developing

**Comment by adamdecaf** [comment]
Should we remove that docker-compose file then? I missed it before.

**Comment by jvehent** [comment]
done
