### ISSUE TITLE
Root store results do not match current Firefox

### ISSUE THREAD

**Issue by jryans** [mozilla/tls-observatory#395]
When running the [TLS observatory scan](https://observatory.mozilla.org/analyze/modular.im#tls) for some sites such as `modular.im`, we see the Symantec distrust warning even though the site loads just fine in modern browsers.

Looking at the [cert chain](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=188209994) for this site we see:

<img width="632" alt="2019-11-13 at 15 08" src="https://user-images.githubusercontent.com/279572/68776154-87335180-0627-11ea-9e6e-33f8b3bfb9e5.png">

Looking at the [TLS observatory results](https://tls-observatory.services.mozilla.com/api/v1/results?id=38894498), we find in the analysis section:

<img width="930" alt="2019-11-13 at 15 10" src="https://user-images.githubusercontent.com/279572/68776367-dbd6cc80-0627-11ea-8a92-51ec0f03f559.png">

that it states it was marked distrusted by `symantecDistrust` because `"path uses a root not trusted by Mozilla: C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root (id=16)"`. This CA root does not have a connection to Symantec, but it was still logged as a failure by the Symantec-checker because the observatory thinks the CA root is not in the Mozilla trust store:

https://github.com/mozilla/tls-observatory/blob/a3c1b6cfecfd7a0cf8f64c6bdc2b1e1d6a87e06c/worker/symantecDistrust/symantecDistrust.go#L251-L255 

Looking at the code for [observatory website](https://github.com/mozilla/http-observatory-website/blob/5208edb18f4f03e7052679f9d4bb797be82aa869/src/js/observatories/tls.js#L197), we see that the Symantec warning in the UI is shown for **any** failure from `symantecDistrust`, even this one which has no connection to Symantec.

Although the [cert explainer](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=16) claims the Baltimore CyberTrust Root is not in any trust store, **it is present** in Firefox 72 and **it is included** in the [current version](https://hg.mozilla.org/mozilla-central/raw-file/2f19e7b646e0a52fa855b75c868f0a3f3a990ad3/security/nss/lib/ckfw/builtins/certdata.txt) of the Mozilla root cert store (search for `D4:DE:20:D0:5E:66:FC:53:FE:1A:50:88:2C:78:DB:28:52:CA:E4:74`).

I believe this means the observatory is using outdated or incorrect info when determining whether a CA root cert is in the trust store, and thus indirectly marking all such sites as connected to Symantec incorrectly.

**Comment by g-k** [comment]
Ah, the column for the Mozilla truststore in CCADB changed. Fixed in https://github.com/mozilla/tls-observatory/pull/417 then had to wait for the backlog to clear. 

TLS Obs now shows:

![image](https://user-images.githubusercontent.com/226605/105723863-430f3280-5ef5-11eb-8cd6-4b195399f390.png)

in scan https://tls-observatory.services.mozilla.com/api/v1/results?id=42297239

So I think we're all set here.
