### ISSUE TITLE
Remove `in_*_root_store` columns from certificate table

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#69]
Unless I'm mistaken, those columns are not used anymore, in favor of the `trust` table. Can we remove them from the schema entirely?

**Comment by 0xDiBa** [comment]
I can see in the code that it is currently used.
If we can get something out of them is another story though.

These fields are only used in root CA certs and their only use would be if we want an
easy and quick way to see the certificates that are currently in any given truststore.
If we don't have a use case for that I think they can go.

**Comment by jvehent** [comment]
Haaa, now that makes sense. I misunderstood the meaning of the column, but it seems logical that it would indicate presence in the trust store.
