### ISSUE TITLE
`subjectPublicKeyInfo` is not stored in database

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#72]
It appears that `subjectPublicKeyInfo` related fields are empty in database. They need to be added in the scanner, and a script need to be written to populate the values for existing certs, same as `fixvalidity.go`.

**Comment by 0xDiBa** [comment]
Exactly what fields do you mean? The old subjectPublicKeyInfo struct has a lot of fields
which are not at all present in the current database schema.

Should we include all of them?

**Comment by jvehent** [comment]
I didn't dig through the code yet, but if you look [at this certificate](https://tls-observatory.services.mozilla.com/api/v1/certificate?id=408903), for example, you'll see that the `subjectPublicKeyInfo` section is empty.

**Comment by 0xDiBa** [comment]
[This struct](https://github.com/mozilla/tls-observatory/blob/master/certificate/certificate.go#L71-L82) is not represented in the database. Should we include it as a jsonb field or keep the fields that are of interest and make them columns?

**Comment by jvehent** [comment]
A RSA key looks like this
```
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:bd:ca:99:2c:36:79:51:95:06:d2:5a:b3:b1:12:
                    32:aa:bc:9d:ec:b6:08:5c:ef:84:29:61:03:9e:4e:
                    e8:0f:9c:e1:8c:b7:b7:bb:21:47:ec:6a:cf:3f:44:
                    6c:e4:72:70:70:d3:39:9c:b2:6a:c8:db:c3:6e:21:
                    b5:28:8a:3a:18:08:b5:32:6c:48:ec:49:d1:eb:d0:
                    0d:db:c1:95:34:11:fc:2c:8a:b3:4b:dd:d0:87:44:
                    57:3e:a7:c1:05:b0:cd:c7:46:9e:72:cf:24:2b:8d:
                    d6:de:5d:92:4b:74:66:32:e4:63:42:4a:6f:53:f4:
                    f1:60:4c:64:cb:7f:c4:30:5a:88:f6:4c:91:7a:f3:
                    6b:05:92:d8:98:99:e6:a7:34:5f:e2:03:ba:03:1c:
                    92:23:16:b8:3b:fc:32:dc:9f:7c:42:3f:f2:1e:7b:
                    81:30:be:f9:93:cb:37:31:5b:76:c7:aa:3c:ec:9f:
                    c0:0e:43:fb:6e:5a:10:29:f2:89:1e:c8:f1:9a:48:
                    db:c3:eb:e9:aa:b8:62:c8:9e:2e:be:4e:a4:38:87:
                    b0:39:36:08:01:3e:29:12:d0:18:2e:24:bc:72:03:
                    ac:05:ea:0d:f4:44:e8:a4:00:51:99:f3:dd:7c:52:
                    34:c8:19:f3:26:4f:c9:ab:a9:5c:68:dd:4c:ab:3f:
                    ec:25
                Exponent: 65537 (0x10001)
```
And an ECDSA one like this:
```
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub: 
                    04:a5:23:7f:5d:35:76:11:46:1b:a2:31:f2:42:23:
                    1a:dc:49:63:1f:78:fc:79:8b:52:5a:1b:61:34:ed:
                    0a:e7:6d:b3:a1:b5:64:e3:a9:e4:cc:ed:4e:28:f9:
                    c2:49:a1:4c:38:fe:79:22:2b:6b:65:03:92:bd:b9:
                    cf:7f:25:49:f6:08:fb:1f:98:f3:47:2b:8d:70:82:
                    d7:25:53:a2:7e:3d:88:07:90:07:a4:35:62:ab:95:
                    ae:0f:84:27:7e:b7:65
                ASN1 OID: secp384r1
                NIST CURVE: P-384
```
The only common element is the Public Key Algorithm, so I think we should put that in its own column, and the rest in a jsonb column.
```
public_key_algo string
public_key_info jsonb
```
What do you think?

**Comment by 0xDiBa** [comment]
That will work.
I will go through all these minor issues we've created probably tomorrow and write some code to 
fix them.

**Comment by jvehent** [comment]
Argh, this is blocking the cert type test in the evaluation worker. Once this issue is fixed, we can fix #86.

**Comment by 0xDiBa** [comment]
I looked into that last week.
I have yet to extract the pub field of the ecdsa keys. We may also want to create mappings for the curve types from go names to openssl names 
for better searching.

**Comment by jvehent** [comment]
We use Go names for signature algorithms, so it would make sense to use Go names for curve types as well. Mapping with OpenSSL names would be good, I did some in the eval worker. I wonder where that would fit best: in the doc, or in a separate table in the database.
