### ISSUE TITLE
weird results scanning site that use symantec's CA

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#73]
When scanning `avvillas.com.co`, the observatory fails to parse the target cert correctly, but instead shows bogus results about its signing cert. The issue seem to be somewhere in the cert retriever.

**Comment by 0xDiBa** [comment]
The server provides the VeriSign, Inc. Class 3 Public Primary Certification Authority root certificate which is a version 2 certificate that does not have a CA field. 
The analyser code sees it as a second non-CA certificate in the chain and kinda loses it... :dizzy_face: 

We handled this type of certs when loading the certificate truststores but did not account for them when handling certificate validation. 

I am pushing a patch which will solve the current issue and will check for a more robust solution ( maybe see what other libs are doing ) in the upcoming analyser code cleaning I have in mind.

**Comment by jvehent** [comment]
Tested the hotfix and it does fix the issue. Is it good enough to close this, or do you want to keep it open to discuss a more robust approach?

**Comment by 0xDiBa** [comment]
I think the discussion going on around the commit will be enough.
After all it is an issue of the general approach and not the specific website or certificate.
