### ISSUE TITLE
x509_certificatePolicies results always empty

### ISSUE THREAD

**Issue by marumari** [mozilla/tls-observatory#74]
>```SELECT x509_certificatePolicies FROM certificates WHERE subject LIKE '%.mozilla.org';```

(103 results, no output)

**Comment by jvehent** [comment]
I can't find any mention of it in the [certificate](https://github.com/mozilla/tls-observatory/blob/master/certificate/certificate.go) package. It only appears in the database schema. So I'm going to guess it's not yet implemented.
