### ISSUE TITLE
scans are not processing

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#79]
I deployed the latest HEAD in stage and scans are not processing anymore. I think it may be related to https://github.com/mozilla/tls-observatory/commit/0c684399cfce3f704a3cc3b91bbb31fc904ebf53 but haven't had time to debug yet. In the database, new scans stay unacknowledged, as if the notification channel was broken.
@0xDiBa: can you test on your dev instance?

**Comment by 0xDiBa** [comment]
That would be weird.
I hope I did not really mess something up.
I will check it out asap.

**Comment by 0xDiBa** [comment]
Just tested it.
Works fine with latest commit 5a8c5bb.
Weird problem...

**Comment by jvehent** [comment]
Issue is gone. might just have been a blip on the server side.
