### ISSUE TITLE
Show already indexed results when fresh scan exists

### ISSUE THREAD

**Issue by 0xdiba** [mozilla/tls-observatory#84]
Would it be useful to change the scan endpoint so it searches the database for the requested domain before initiating a new scan. If a scan within a certain time period is found ( eg 1-2 days or maybe a little more ) its id is returned to the client instead of a new one.

It is surely not an urgent matter but it would probably save us a lot of space and processing time when the API becomes public...

Of course this will not affect the programmed recurring scans and we can even add a ```force=true``` argument to the endpoint to force a scan even if one that meets our criteria is already in the DB.

**Comment by jvehent** [comment]
Agreed. And :+1: for the `force=true` argument (maybe name it `rescan` or something more explicit).

May the force be with you.

**Comment by jvehent** [comment]
fixed by #94
