### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by 0xdiba** [mozilla/tls-observatory#90]
Should we create a gh page with some basic info about the project along with an api documentation?

**Comment by jvehent** [comment]
@marumari is taking a look at a JS webui to the API, so that may need to be hosted somewhere. I'd say let's wait for her work to complete and decide then. You can put doc in the Readme for now, we can always move it later.

**Comment by 0xdiba** [comment]
The webUI might bring back the OAuth implementation though ;)

**Comment by jvehent** [comment]
For now, all data is public. I'd prefer to have sane limits in place and not require authentication, but we'll see how it goes.

**Comment by marumari** [comment]
I don't know if the API really allows me to make much of a webUI around it currently.  Kicking off scans and seeing the results is great, but I really want to be able to search and see old results, especially by doing queries like *.mozilla.org and the like.

**Comment by 0xdiba** [comment]
Simple documentation is provided in the README
