### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by jvehent** [mozilla/tls-observatory#91]
Discuss implementing a thin UI around the API.

**Comment by jvehent** [comment]
Blocked by #84, #72, #92

**Comment by marumari** [comment]
You can now start to see the beginning of the web interface included in the "Mozilla Observatory":

https://mozilla.github.io/http-observatory-website/analyze.html?host=pokeinthe.io

Much more in the days to come!

**Comment by jvehent** [comment]
@marumari is spearheading that one.

**Comment by marumari** [comment]
I love web gooeys!
